name: Presubmit
on: [push, pull_request]

jobs:
  build:
    name: Generate all specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install required packages
        run: |
          sudo apt-get install -y libpango1.0-dev ghostscript fonts-lyx
          sudo gem install asciidoctor -v 1.5.8
          sudo gem install coderay -v 1.1.1
          sudo gem install ttfunk -v 1.5.1
          sudo gem install asciidoctor-pdf -v 1.5.0
          sudo MATHEMATICAL_SKIP_STRDUP=1 gem install asciidoctor-mathematical -v 0.2.2
      - name: Generate all specs
        run: |
          git describe --tags --dirty
          make api c env ext cxx4opencl
          make extensionshtml
